// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo-OpZnTwwTsHYMBua3L1_qcj81GrfGo0',
    appId: '1:1005594903686:web:10a20b59b86cd413acbd07',
    messagingSenderId: '1005594903686',
    projectId: 'neurobridge-backend',
    authDomain: 'neurobridge-backend.firebaseapp.com',
    storageBucket: 'neurobridge-backend.firebasestorage.app',
    measurementId: 'G-4V54BB8LEP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcZ7vlvcgcFdUlPblBWxCW0RteSg6i97E',
    appId: '1:1005594903686:android:c8d043b328d439b9acbd07',
    messagingSenderId: '1005594903686',
    projectId: 'neurobridge-backend',
    storageBucket: 'neurobridge-backend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx3HBhJLnUZ0jH9zOb7Dn1f3F6N0C0Ofc',
    appId: '1:1005594903686:ios:b5ef15195b56ed92acbd07',
    messagingSenderId: '1005594903686',
    projectId: 'neurobridge-backend',
    storageBucket: 'neurobridge-backend.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx3HBhJLnUZ0jH9zOb7Dn1f3F6N0C0Ofc',
    appId: '1:1005594903686:ios:b5ef15195b56ed92acbd07',
    messagingSenderId: '1005594903686',
    projectId: 'neurobridge-backend',
    storageBucket: 'neurobridge-backend.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBo-OpZnTwwTsHYMBua3L1_qcj81GrfGo0',
    appId: '1:1005594903686:web:e127d9b39dbc5201acbd07',
    messagingSenderId: '1005594903686',
    projectId: 'neurobridge-backend',
    authDomain: 'neurobridge-backend.firebaseapp.com',
    storageBucket: 'neurobridge-backend.firebasestorage.app',
    measurementId: 'G-JDEJQN88QL',
  );
}
